### PR TITLE
Papymaj5/apollo sys checks

### PR DESCRIPTION
**Pull request by papymaj5**
- Removed old System Checklists that are inside of either TLI, EPS, or ECS checklists
- Full formatting of ECS, EPS, and Propulsion checklists

### CODE REVIEW

**Comment by sundhaug92** [comment]
@papymaj5 Conflicts

**Comment by papymaj5** [comment]
@sundhaug92 these PRs are old and have been broken from all the changes @petriw has been making. I am waiting for his go ahead to update these. He previously said, on discord, he had to make a bunch of changes first.

**Comment by papymaj5** [comment]
These probably need to just be abandoned at this point.

**Comment by sundhaug92** [comment]
Yeah, @petriw thoughts?

**Pull request closed without merging**
