### PR TITLE
Here is the LOI 

### PR DESCRIPTION
**Pull request by 343GuiltySpark-04**
I added an SPS Burn/LOI checklist @sundhaug92

### CODE REVIEW

**Review by sundhaug92 — COMMENTED** [review]
Note, this includes the Mercury cl text re accidental retro jett

**Comment by 343GuiltySpark-04** [comment]
yeah I forgot to create a PR for the revised one so decided to leave it (I also don't know how to exclude specific commits or if thats even possible)

**Comment by sundhaug92** [comment]
It's possible to use `git squash` to remove a commit from a branch

**Comment by sundhaug92** [comment]
Note: Labeler fails because it's using the old v2 labeler, rather than the new v3 I just merged with #28.

**Comment by 343GuiltySpark-04** [comment]
> It's possible to use `git squash` to remove a commit from a branch

is it possible to do that in the github web page or will I have to do it in the command line after lunch?

**Comment by 343GuiltySpark-04** [comment]
> Note: Labeler fails because it's using the old v2 labeler, rather than the new v3 I just merged with #28.

if you want something done right lol

**Comment by sundhaug92** [comment]
> > It's possible to use `git squash` to remove a commit from a branch
> 
> is it possible to do that in the github web page or will I have to do it in the command line after lunch?

AFAIK no, but you can do an interactive squash, which will open your editor and ask you to edit it that way

**Comment by 343GuiltySpark-04** [comment]
> > > It's possible to use `git squash` to remove a commit from a branch
> > 
> > is it possible to do that in the github web page or will I have to do it in the command line after lunch?
> 
> AFAIK no, but you can do an interactive squash, which will open your editor and ask you to edit it that way

editor In the command line or editor in the github page?

**Comment by sundhaug92** [comment]
> > > > It's possible to use `git squash` to remove a commit from a branch
> > > 
> > > 
> > > is it possible to do that in the github web page or will I have to do it in the command line after lunch?
> > 
> > 
> > AFAIK no, but you can do an interactive squash, which will open your editor and ask you to edit it that way
> 
> editor In the command line or editor in the github page?

editor as in your local editor (vscode, notepad, emacs, vim, nano, ...)

**Comment by 343GuiltySpark-04** [comment]
> > > > > It's possible to use `git squash` to remove a commit from a branch
> > > > 
> > > > 
> > > > is it possible to do that in the github web page or will I have to do it in the command line after lunch?
> > > 
> > > 
> > > AFAIK no, but you can do an interactive squash, which will open your editor and ask you to edit it that way
> > 
> > editor In the command line or editor in the github page?
> 
> editor as in your local editor (vscode, notepad, emacs, vim, nano, ...)

ah ok

**Comment by sundhaug92** [comment]
Closing while we unfudge stuff

**Pull request closed without merging**
