### PR TITLE
Formatting & Restructure of Activation, Backup Crew, and Pre-Flight Checklists

### PR DESCRIPTION
**Pull request by papymaj5**
- Full formatting updates to Activation, Backup Crew, and Pre-Flight Checklists
  - Did not touch runs and there are probably updates needed
  - Updated ActivationActivation/checklist.json IAW last IMU Align commit
- Removed Preflight/Preflight checklist as redundant
- Merged Backup Crew checklists to make a smaller footprint

### CODE REVIEW

**Comment by sundhaug92** [comment]
@papymaj5 PR conflicts

**Comment by papymaj5** [comment]
@sundhaug92 these PRs are old and have been broken from all the changes @petriw has been making. I am waiting for his go ahead to update these. He previously said, on discord, he had to make a bunch of changes first.

**Comment by papymaj5** [comment]
These probably need to just be abandoned at this point.

**Comment by sundhaug92** [comment]
@petriw

**Pull request closed without merging**
