### PR TITLE
DSKY Quick Reference Handbook Initial Commit

### PR DESCRIPTION
**Pull request by Valkyrien04**
Creates an in game QRH for DSKY Nouns, Verbs, and Currently Implemented Programs up through P40. P60-69 to follow after some work on entry checklists.

### CODE REVIEW

**Comment by petriw** [comment]
Hi!
could you post a link to the reference/source of these checklists?
Thanks!

**Comment by Sophie-Hawley** [comment]
Reference for the programs was the game manual as is here: https://reentrygame.com/gamemanuals/ProjectApolloGameManual.pdf

Nouns and Verbs were collected from this PDF, which i believe might be part of the NASSP project but i could be wrong: https://www.ibiblio.org/apollo/CMC_data_cards_15_Fabrizio_Bernardini.pdf

**Comment by Sophie-Hawley** [comment]
Addtl changes merged (P15 and nouns)

**Comment by sundhaug92** [comment]
@petriw No conflict

**Review by petriw — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
