### PR TITLE
Fix typo to account for keyboards lacking a shit key

### PR DESCRIPTION
**Pull request by sundhaug92**

### CODE REVIEW

**Comment by 343GuiltySpark-04** [comment]
I vote keep the shit key, may be helpful if imminent RUD

**Comment by 343GuiltySpark-04** [comment]
however it should be ctrl+O+shit

**Comment by 343GuiltySpark-04** [comment]
still cant find the shit key @sundhaug92 lol

**Review by petriw — APPROVED** [review]
Thanks!

**Pull request merged**
