### PR TITLE
LOI V2

### PR DESCRIPTION
**Pull request by 343GuiltySpark-04**
Heres the one me and @sundhaug92 fixed, i also made it partaly runnable

### CODE REVIEW

**Comment by sundhaug92** [comment]
ty, could you pull a8a803b92e747500d0d27594eee997a1cef138f5 into your `main`?

`git pull https://github.com/ReentryGame/DefaultChecklists`

**Comment by 343GuiltySpark-04** [comment]
sure but tick tock, i dont have much time 

image

**Comment by 343GuiltySpark-04** [comment]
also how

**Comment by 343GuiltySpark-04** [comment]
also fixed a typo in the post LM docking Checklist.

**Comment by 343GuiltySpark-04** [comment]
is it me or is does petri procrastinate more than me lol

**Review by petriw — APPROVED** [review]
Thanks! Merging in the SPS Burn and LOI checklist, will process it locally.

**Comment by 343GuiltySpark-04** [comment]
no problem, after I finish the halo infinite campaign I plan on making a TEI checklist too.

**Pull request merged**
