### PR TITLE
Feature/gemini updates

### PR DESCRIPTION
**Pull request by papymaj5**
This PR included substantial updates to the preflight, insertion, retro & entry, and the landing phases. These changes are based on the Gemini 10 Flight Plan and have been tested in Reentry.

### CODE REVIEW

**Comment by sundhaug92** [comment]
Hi, noticing a few files deleted?

**Comment by papymaj5** [comment]
> Hi, noticing a few files deleted?

Hi! Yes, I added PreRetro, Tr -256 sec, and Tr -1min checklists, these replaced the Tr -5min, Tr -30 sec, and Retro Jettison checklists. The Tr -1min checklist goes through JETT RETRO. 

Here is the reference I used: http://digitalsc.lib.vt.edu/Ms1989-029/Ms1989-029_B03_F7b

**Comment by papymaj5** [comment]
I have made some additional changes which I will merge into this PR. Though I would like to go over how the RE ENTRY Computer works with the ACME in RE ENTRY mode. I don't see the automatic taking over at all. Following the Reentry checklist and the Gemini 10 checklist yields the same results. If anyone is interested in doing a screen share or something on discord that would be helpful. papymaj5#5217

**Review by sundhaug92 — COMMENTED** [review]
Nice, though this seems to only have one step

**Comment by petriw** [comment]
@papymaj5 I have re-wired the X OVER switch to id=205. Could you change line 1196 in the "PreFlightInteriorInspection" from "SetID": 0, to "SetID": 205? This will not work in the current default branch before I release 0.84, but the alpha branch should have the change to make this runnable.

**Review by petriw — APPROVED** [review]
Great contribution. I will start to wire this in.

**Pull request merged**
