### PR TITLE
Papymaj5 mercury updates

### PR DESCRIPTION
**Pull request by papymaj5**
Bunch of updates to the Mercury Checklists, mostly QOL updates and formatting.

### CODE REVIEW

**Comment by sundhaug92** [comment]
Mercury/AscentAscent/checklist.json now lacks steps

**Comment by sundhaug92** [comment]
Mercury/EmergencyAscent/checklist.json typo "SHIT"

**Comment by papymaj5** [comment]
> Mercury/AscentAscent/checklist.json now lacks steps

This is the my version ascent checklist
image

I can put both options to start BECO or REDSTONE, but i'd rather not have both if one will not be used.

**Comment by sundhaug92** [comment]
> > Mercury/AscentAscent/checklist.json now lacks steps
> 
> This is the my version ascent checklist image
> 
> I can put both options to start BECO or REDSTONE, but i'd rather not have both if one will not be used.

Original was executable, but looking at it now perhaps it shouldn't be? @petriw

**Comment by papymaj5** [comment]
> Mercury/EmergencyAscent/checklist.json typo "SHIT"

I just fixed this in my last commit

> Original was executable, but looking at it now perhaps it shouldn't be? @petriw

If we could use a conditional statement for checklist items.

**Review by petriw — APPROVED** [review]
Thanks for the contribution! Will start to process these.

**Pull request merged**
